// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ResourcesId } from './Resources';

/** Represents the table content.date_events */
export default interface DateEvents {
  resource_id: ResourcesId;

  date: string;

  title: string;

  exact_date: Date;

  description?: string;

  image_url?: string;

  link_url?: string;
}

/** Represents the initializer for the table content.date_events */
export interface DateEventsInitializer {
  resource_id: ResourcesId;

  date: string;

  title: string;

  exact_date: Date;

  description?: string;

  image_url?: string;

  link_url?: string;
}

/** Represents the mutator for the table content.date_events */
export interface DateEventsMutator {
  resource_id?: ResourcesId;

  date?: string;

  title?: string;

  exact_date?: Date;

  description?: string;

  image_url?: string;

  link_url?: string;
}
